--  INSERT INTO txnDetails VALUES (NULL,'LOAN','BODABODALOAN','LOANDISBURSEMENT'),(NULL,'LOAN','BODABODALOAN','LOANPAYMENT'),(NULL,'LOAN','TAXILOAN','LOANDISBURSEMENT'),(NULL,'LOAN','TAXILOAN','LOANPAYMENT'),(NULL,'LOAN','MICROLOAN','LOANDISBURSEMENT'),(NULL,'LOAN','MICROLOAN','LOANPAYMENT'),(NULL,'LOAN','STAFFLOAN','LOANDISBURSEMENT'),(NULL,'LOAN','STAFFLOAN','LOANPAYMENT'),(NULL,'SAVING','BOBABODASAVING','SAVINGDEPOSIT'),(NULL,'SAVING','BOBABODASAVING','SAVINGWITHDRAWAL'),(NULL,'SAVING','TAXISAVING','SAVINGDEPOSIT'),(NULL,'SAVING','TAXISAVING','SAVINGWITHDRAWAL'),(NULL,'SAVING','INDIVIDUALSAVING','SAVINGDEPOSIT'),(NULL,'SAVING','INDIVIDUALSAVING','SAVINGWITHDRAWAL'),(NULL,'FLOAT','FLOANTXN','FLOATDEPOSIT'),(NULL,'FLOAT','FLOANTXN','FLOATWITHDRAWAL'),(NULL,'EXPENSE','EXPENSETXN','EXPENSETXN1');


--  INSERT INTO itemRequiringApprovalCreate VALUES (NULL,'AREA_CREATION',0,1,2,3,4,5),(NULL,'TOWN_CREATION',0,1,2,3,4,5),(NULL,'STATION_CREATION',0,1,2,3,4,5),(NULL,'WAVING_INTEREST',0,1,2,3,4,5),(NULL,'SETTING_DEFAULT_STATION_INTERESTRATE',0,1,2,3,4,5),(NULL,'SETTING_DEFAULT_STATION_LOANLIMIT',0,1,2,3,4,5),(NULL,'CHANGING_INDIVIDUAL_INTERESTRATE',0,1,2,3,4,5),(NULL,'CHANGING_INDIVIDUAL_LOANLIMIT',0,1,2,3,4,5),(NULL,'WRITTING_OFF_PRINCIPAL',0,1,2,3,4,5),(NULL,'REVERSING_PRINCIPAL',0,1,2,3,4,5),(NULL,'CREATING_CUSTOMER',0,1,2,3,4,5),(NULL,'CREATING_MICROLOAN',0,1,2,3,4,5),(NULL,'WITHDRAWAL_OF_SAVINGS',0,1,2,3,4,5),(NULL,'USER_REGISTRATION',0,1,2,3,4,5);


--  INSERT INTO itemRequiringApprovalUpdate VALUES (NULL,'AREA_UPDATE',0,1,2,3,4,5),(NULL,'TOWN_UPDATE',0,1,2,3,4,5),(NULL,'STATION_UPDATE',0,1,2,3,4,5),(NULL,'UPDATING_CUSTOMER',0,1,2,3,4,5),(NULL,'UPDATING_USER_PROFILE',0,1,2,3,4,5);



